version: '3.1'

services:

    blazegraph:
        image: conjecto/blazegraph:2.1.5
        container_name: blazegraph
        restart: always
        ports:
          - 9999:9999
        environment:
            JAVA_OPTS: "-Xms2g -Xmx3g"
        volumes:
          - ./dataset:/docker-entrypoint-initdb.d

    datatourisme:
        container_name: datatourisme
        build: docker
        ports:
            - "8000:90"
        restart: always
        depends_on:
            - blazegraph

volumes:
  caddy_data:
  caddy_config:

